### ISSUE TITLE
When user post something on channel show it

### ISSUE THREAD

**Issue by mitjap** [wlanslovenija/PiplMesh#308]
Current implementation notifies user about incoming posts but does not display it. Make necessary changes so posts from user will always show immediately after post.

**Comment by mitar** [comment]
Related: #163

**Comment by mitjap** [comment]
In case user has slow connection i guess post should be displayed before we get response from server. This could be tricky to implement thought.

**Comment by mitar** [comment]
No. There is nothing wrong if there is a delay. Also Facebook has it. So we just have to provide some feedback (processing/loading). Because sometimes we will want also to do some spam checking and stuff.

The other way is also that we configure Tastypie to return full object not successful post, not just URI.

**Comment by mitar** [comment]
Anyway, this is probably just an if-sentence, if author == current user, display, otherwise go into current logic.
